// Builds everything that ships from this folder:
//   dist/extension/          the browser extension (load unpacked from here)
//   dist/inpage.embedded.js  the provider MiniGo injects into mini apps
//   dist/kit/                the Stellar Wallets Kit module, as an ES module
// and copies the embedded provider into the MiniGo app and the test mini app.
import { build } from "esbuild";
import { cpSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dist = join(root, "dist");
const ext = join(dist, "extension");
rmSync(dist, { recursive: true, force: true });
mkdirSync(ext, { recursive: true });

const common = { bundle: true, target: "es2020", legalComments: "none", logLevel: "warning" };

// In-page providers: small, no Stellar SDK inside.
for (const [file, compat] of [["inpage.js", false], ["inpage.freighter.js", true]]) {
  await build({ ...common, entryPoints: [join(root, "src/inpage/extension.ts")], outfile: join(ext, file), format: "iife", minify: true, define: { __FREIGHTER_COMPAT__: String(compat) } });
}
await build({ ...common, entryPoints: [join(root, "src/inpage/embedded.ts")], outfile: join(dist, "inpage.embedded.js"), format: "iife", minify: true });

// Extension pages and worker.
for (const name of ["background", "relay", "popup", "approve"]) {
  await build({ ...common, entryPoints: [join(root, `extension/src/${name}.ts`)], outfile: join(ext, `${name}.js`), format: "iife", platform: "browser" });
}
for (const file of ["manifest.json", "popup.html", "approve.html", "style.css"]) cpSync(join(root, "extension", file), join(ext, file));

// Wallets Kit module for dApps that install it from npm.
await build({ ...common, entryPoints: [join(root, "src/kit/minigo.module.ts")], outfile: join(dist, "kit/minigo.module.js"), format: "esm", external: ["@creit.tech/stellar-wallets-kit"] });

// Hand the embedded provider to MiniGo and to the test mini app.
const embedded = readFileSync(join(dist, "inpage.embedded.js"), "utf8").trim();
writeFileSync(
  join(root, "../minigo/src/mini/inpage.generated.ts"),
  `// Generated by minigo-wallet-sdk (npm run build). Do not edit: change minigo-wallet-sdk/src/inpage instead.\n` +
    `// The SEP-43 window.mini provider plus the Freighter fallback, injected before a mini app's own scripts.\n` +
    `export const inpageProvider = ${JSON.stringify(embedded + "\ntrue;")};\n`,
);
writeFileSync(
  join(root, "../test-mini-app/public/minigo.js"),
  `/* MiniGo in-page provider (generated by minigo-wallet-sdk). Inside the MiniGo app it's injected already and this does nothing. */\n${embedded}\n`,
);

const size = (file) => `${(readFileSync(file).length / 1024).toFixed(1)} kB`;
console.log(`built: extension (inpage ${size(join(ext, "inpage.js"))}, background ${size(join(ext, "background.js"))}), embedded provider ${size(join(dist, "inpage.embedded.js"))}, kit module`);
